/** Keep in sync with backend `PetBreed` enum values. */
export const PET_BREEDS = [
  "Golden Retriever",
  "Labrador Retriever",
  "German Shepherd",
  "French Bulldog",
  "Bulldog",
  "Poodle",
  "Beagle",
  "Rottweiler",
  "Dachshund",
  "Yorkshire Terrier",
  "Boxer",
  "Siberian Husky",
  "Australian Shepherd",
  "Cavalier King Charles Spaniel",
  "Shih Tzu",
  "Boston Terrier",
  "Pomeranian",
  "Havanese",
  "Shetland Sheepdog",
  "Border Collie",
  "Chihuahua",
  "Maltese",
  "Cocker Spaniel",
  "Pug",
  "Great Dane",
  "Doberman Pinscher",
  "Miniature Schnauzer",
  "Bernese Mountain Dog",
  "Akita",
  "American Pit Bull Terrier",
  "Staffordshire Bull Terrier",
  "Mastiff",
  "Basset Hound",
  "Weimaraner",
  "Vizsla",
  "Samoyed",
  "Alaskan Malamute",
  "English Springer Spaniel",
  "Brittany",
  "Collie",
  "Newfoundland",
  "Rhodesian Ridgeback",
  "West Highland White Terrier",
  "Scottish Terrier",
  "Airedale Terrier",
  "Whippet",
  "Greyhound",
  "Persian",
  "Maine Coon",
  "Siamese",
  "Ragdoll",
  "Bengal",
  "British Shorthair",
  "Abyssinian",
  "Scottish Fold",
  "Sphynx",
  "Domestic Shorthair",
  "Domestic Longhair",
  "Mixed breed",
  "Other",
] as const;

export const OTHER_BREED = "Other" as const;

export type PetBreed = (typeof PET_BREEDS)[number];

export const PET_BREED_OPTIONS = PET_BREEDS.map((breed) => ({
  value: breed,
  label: breed,
}));
